import {useState} from 'react';
import {Lang} from './i18n';
import {labels,errorText} from './platform-copy';
import {api,AccountState} from './api';
import Brand from './Brand';
import Icon from './Icon';
export default function Auth({lang,onLanguage,onSuccess,onDemo}:{lang:Lang;onLanguage:()=>void;onSuccess:(s:AccountState)=>void;onDemo:()=>void}){
 const c=labels(lang),[register,setRegister]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <div className="auth-shell"><header className="portal-header"><Brand/><button className="language" onClick={onLanguage}>{lang==='ar'?'English':'العربية'}</button></header><main className="auth-grid"><section className="auth-editorial"><span className="section-kicker">AZM / PERSONAL MOVEMENT</span><h1>{c.authTitle}</h1><p>{c.authBody}</p><div className="auth-athlete"><img src="/illustrations/standing.png" alt={lang==='ar'?'رسم توضيحي لرياضي':'Athlete illustration'}/><span className="auth-orbit"/><div className="auth-index"><span>01 — 03</span><b>{lang==='ar'?'اعرف نقطة البداية.\nوابنِ عليها.':'Find your starting point.\nBuild from there.'}</b></div></div></section><section className="auth-form-panel"><div className="auth-tabs"><button className={!register?'active':''} onClick={()=>{setRegister(false);setError('');}}>{c.login}</button><button className={register?'active':''} onClick={()=>{setRegister(true);setError('');}}>{c.register}</button></div><h2>{register?c.register:c.login}</h2><p>{c.authFoot}</p><form onSubmit={async e=>{e.preventDefault();const data=new FormData(e.currentTarget);setBusy(true);setError('');try{onSuccess(await api(`/auth/${register?'register':'login'}`,Object.fromEntries(data)));}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}>{register&&<label className="field"><span>{c.name}</span><input name="name" autoComplete="name" required minLength={2} maxLength={80}/></label>}<label className="field"><span>{c.email}</span><input name="email" type="email" autoComplete="email" required dir="ltr" maxLength={254}/></label><label className="field"><span>{c.password}</span><input name="password" type="password" autoComplete={register?'new-password':'current-password'} minLength={10} maxLength={128} required dir="ltr"/><small>{c.passwordHint}</small></label>{error&&<p className="form-error" role="alert">{errorText(error,lang)}</p>}<button className="cta" disabled={busy}>{busy?c.busy:register?c.register:c.login}<Icon name="arrow" size={18}/></button></form><button className="auth-demo text-button" onClick={onDemo}><Icon name="play" size={16}/>{c.demo}</button></section></main></div>;
}
