import { Lang } from './i18n';

const ar = {
 steps: ['وضعيتك', 'ثبّت جوالك', 'الكاميرا'],
 poseTitle: 'كيف ستتمرّن الآن؟',
 poseBody: 'اختر الوضعية التي ستتمرّن منها، ونجهّز لك الحركة المناسبة لها.',
 poses: {
  chair: { title: 'جالسًا على كرسي', body: 'ضغط الكتف جالسًا' },
  wheelchair: { title: 'من كرسيك المتحرك', body: 'ضغط الكتف جالسًا' },
  rise: { title: 'أستطيع النهوض والوقوف', body: 'النهوض من الكرسي' },
 },
 next: 'التالي',
 back: 'رجوع',
 placeTitle: 'ثبّت جوالك، ثم ابتعد عنه',
 placeBody: 'ستتمرّن ويداك حرّتان، والكاميرا تتابعك من مكانها طوال الجلسة.',
 tips: [
  { title: 'اسنده ليقف ثابتًا', body: 'على طاولة أو رف بمستوى صدرك، والشاشة متجهة إليك.' },
  { title: 'ابتعد مترين تقريبًا', body: 'حتى يظهر رأسك وكتفاك وذراعاك كاملة في الصورة.' },
  { title: 'اجعل الضوء أمامك', body: 'النافذة أو المصباح خلفك يخفي حركتك عن الكاميرا.' },
  { title: 'ارفع صوت الجوال', body: 'مدرّب بصوت عربي يعدّ معك ويصحّح لك أثناء الحركة.' },
 ],
 tipRise: 'حتى يظهر جسمك كاملًا مع الكرسي، من رأسك إلى قدميك.',
 start: 'شغّل الكاميرا وابدأ',
 simulate: 'لا أريد تشغيل الكاميرا الآن، أرني عرضًا توضيحيًا',
 privacy: 'تُحلَّل الحركة داخل جهازك، ولا يُسجَّل الفيديو ولا يُرفع.',
 live: 'مباشر',
 loadingCam: 'نطلب إذن الكاميرا',
 loadingModel: 'نجهّز تتبع الحركة',
 noPerson: 'لا نراك بعد',
 noPersonBody: 'اجلس أو قف أمام الكاميرا على بعد مترين تقريبًا.',
 partial: 'ابتعد قليلًا',
 partialBody: 'نحتاج أن نرى كتفيك ومرفقيك ويديك بوضوح.',
 partialRise: 'نحتاج أن نرى جسمك كاملًا مع الكرسي.',
 hold: 'ممتاز، اثبت لحظة',
 holdBody: 'نتأكد أن الصورة ثابتة، ثم نبدأ.',
 calTitle: 'نقيس مداك أنت',
 calBody: 'كرّر الحركة ببطء ثلاث مرات، بجهد مريح.',
 lost: 'لا نرى جسمك كاملًا',
 lostBody: 'العدّ ينتظر حتى تعود أمام الكاميرا.',
 reps: 'تكرار',
 range: 'مداك',
 stop: 'إيقاف',
 sound: 'الصوت',
 muted: 'صامت',
 exit: 'خروج',
 errDenied: 'لم نحصل على إذن الكاميرا',
 errDeniedBody: 'اسمح للمتصفح باستخدام الكاميرا من إعدادات الموقع، ثم أعد المحاولة.',
 errNone: 'لم نجد كاميرا على هذا الجهاز',
 errGeneric: 'تعذّر تشغيل الكاميرا',
 errGenericBody: 'أغلق أي تطبيق آخر يستخدم الكاميرا، ثم أعد المحاولة.',
 retry: 'أعد المحاولة',
 watchDemo: 'شاهد عرضًا توضيحيًا',
 trialNote: 'هذه جلسة تجريبية ولا تُحفظ. سجّل مجانًا لتحصل على خطتك الأسبوعية المبنية على حالتك الطبية، وتُحفظ كل جلساتك.',
 register: 'ابدأ مجانًا',
 tryAgain: 'جرّب مرة أخرى',
 placeReminder: 'قبل أن تبدأ',
};

const en: typeof ar = {
 steps: ['Your position', 'Set up your phone', 'Camera'],
 poseTitle: 'How will you train right now?',
 poseBody: 'Choose the position you will train from, and we will set up the right movement for it.',
 poses: {
  chair: { title: 'Seated on a chair', body: 'Seated shoulder press' },
  wheelchair: { title: 'From your wheelchair', body: 'Seated shoulder press' },
  rise: { title: 'I can rise and stand', body: 'Sit to stand' },
 },
 next: 'Next',
 back: 'Back',
 placeTitle: 'Prop up your phone, then step back',
 placeBody: 'You train with your hands free, and the camera follows you from where it stands.',
 tips: [
  { title: 'Stand it up securely', body: 'On a table or shelf at chest height, with the screen facing you.' },
  { title: 'Move about two meters away', body: 'So your head, shoulders, and both arms are fully in the picture.' },
  { title: 'Keep the light in front', body: 'A window or lamp behind you hides your movement from the camera.' },
  { title: 'Turn the volume up', body: 'A coach counts with you and corrects you as you move.' },
 ],
 tipRise: 'So your whole body and the chair are in the picture, head to feet.',
 start: 'Turn on the camera and begin',
 simulate: 'I would rather not use the camera now, show me a demo',
 privacy: 'Movement is analyzed on your device. Video is never recorded or uploaded.',
 live: 'Live',
 loadingCam: 'Asking for camera access',
 loadingModel: 'Preparing movement tracking',
 noPerson: 'We cannot see you yet',
 noPersonBody: 'Sit or stand in front of the camera, about two meters away.',
 partial: 'Move back a little',
 partialBody: 'We need to see your shoulders, elbows, and hands clearly.',
 partialRise: 'We need to see your whole body and the chair.',
 hold: 'Perfect, hold still',
 holdBody: 'Making sure the picture is steady, then we begin.',
 calTitle: 'Measuring your own range',
 calBody: 'Repeat the movement slowly three times, at a comfortable effort.',
 lost: 'We cannot see all of you',
 lostBody: 'Counting waits until you are back in front of the camera.',
 reps: 'reps',
 range: 'Your range',
 stop: 'Stop',
 sound: 'Sound',
 muted: 'Muted',
 exit: 'Exit',
 errDenied: 'Camera permission was not granted',
 errDeniedBody: 'Allow camera access for this site in your browser settings, then try again.',
 errNone: 'No camera was found on this device',
 errGeneric: 'The camera could not start',
 errGenericBody: 'Close any other app using the camera, then try again.',
 retry: 'Try again',
 watchDemo: 'Watch a demo',
 trialNote: 'This is a trial session and is not saved. Start free to get a weekly plan built on your medical condition, with every session saved.',
 register: 'Start free',
 tryAgain: 'Try again',
 placeReminder: 'Before you begin',
};

export const camCopy = (l: Lang) => (l === 'ar' ? ar : en);
