import { Lang } from "./i18n";
import { RepClass } from "../engine/types";
export interface Preferences {
  /**
   * The coach's voice (C40): on gives guidance and counts; off leaves the captions. Off by default
   * (booth v2 A6); the large speaker button of the camera screen turns it on, per device.
   */
  voice: "full" | "off";
  /**
   * The movement check's optional check in (D-016): during a camera test, «هل أنت بخير؟» after 5 s out
   * of the picture or 10 s without movement. Per device, off by default, never used at the booth.
   */
  safetyCheckIn: boolean;
  /** The chosen voice pack (src/app/voicePacks.ts); empty follows the default pack. Per device. */
  voicePack: string;
  /**
   * The movement check's sound check answer on this device (S14b runs on the first home check only,
   * C05): voice or the screen reader; empty until it has been asked.
   */
  checkSound: "" | "voice" | "screenReader";
  /**
   * The live coach «المدرّب المباشر» (product v7 C-5): off by default; on only after the live_coach
   * consent, and only in a v7 build. Per device.
   */
  liveCoach: boolean;
  /** How long the person may pause before their turn ends for the live coach (5.1 silenceMs). */
  coachPause: 800 | 1200 | 1600;
}
export const defaults: Preferences = {
  voice: "off",
  safetyCheckIn: false,
  voicePack: "",
  checkSound: "",
  liveCoach: false,
  coachPause: 800,
};
/**
 * Marks a voice choice made since booth v2. Earlier builds stored their default ("full") whenever any
 * coach setting changed, so a voice stored without this marker was never chosen and reads as off.
 */
const VOICE_MARK = 2;
export function readPreferences(): Preferences {
  try {
    const p = JSON.parse(localStorage.getItem("azm.coach") ?? "{}");
    return {
      voice: p.voiceV === VOICE_MARK && p.voice === "full" ? "full" : "off",
      safetyCheckIn: p.safetyCheckIn === true,
      voicePack: typeof p.voicePack === "string" ? p.voicePack : "",
      checkSound: p.checkSound === "voice" || p.checkSound === "screenReader" ? p.checkSound : "",
      liveCoach: p.liveCoach === true,
      coachPause: p.coachPause === 1200 || p.coachPause === 1600 ? p.coachPause : 800,
    };
  } catch {
    return { ...defaults };
  }
}
export function savePreferences(p: Preferences) {
  try {
    localStorage.setItem("azm.coach", JSON.stringify({ ...p, voiceV: VOICE_MARK }));
  } catch {
    /* Settings still work for this visit. */
  }
}
export type RepMoment = { cls: RepClass; durSec: number; peakPct: number };
export const ui = (lang: Lang) =>
  lang === "ar"
    ? {
        coachSettings: "صوت يناسبك",
        voiceSwitch: "صوت المدرّب",
        voiceSwitchNote: "إرشاد وعدّ أثناء التمرين. تبقى التعليمات مكتوبة دائمًا.",
        preview: "استمع إلى عزم",
        voiceChoice: "اختر الصوت",
        close: "تم",
        voiceNote: "صوت عربي مولّد بالذكاء الاصطناعي، محفوظ داخل التطبيق.",
        voiceBlocked: "لم يعمل الصوت. حاول مرة أخرى؛ التعليمات النصية متاحة.",
        personalize: "خصّص مدرّبك",
        step: "الخطوة",
        next: "التالي",
        side: "من الجانب",
        timeline: "حركتك، تكرارًا بتكرار",
        demoTimeline: "تكرارات المحاكاة",
        noneYet: "تظهر التكرارات هنا مع تقدّم المجموعة.",
        complete: "مكتمل",
        adjust: "مع ملاحظة",
        partial: "مدى أقصر",
        seconds: "ث",
        range: "من مداك الشخصي",
        rep: "التكرار",
        review: "اقرأ تفاصيل الحركة",
        insight: "ما الذي حدث في هذه المجموعة؟",
        insightGood: "اكتملت التكرارات المسجّلة دون ملاحظات تعويضية من التتبّع.",
        insightAdjust: "ظهرت ملاحظات حركة في بعض التكرارات. اختر تكرارًا لمراجعة مداه ووقته.",
        insightPartial:
          "بعض الحركات لم تصل إلى مدى العدّ المحدّد بمعايرتك. تُعرض منفصلة عن التكرارات المكتملة.",
        insightEmpty: "لم تُسجّل تكرارات بعد. يمكنك مراجعة وضع الكاميرا وإعادة المحاولة.",
        completed: "تكرارات مكتملة",
        recent: "آخر الجلسات",
        export: "تنزيل سجلّي",
        exportNote: "ملف يحتوي على أرقام جلساتك فقط، دون صور أو فيديو.",
        resume: "كرّر آخر تمرين",
        continue: "تابع بنفس الإعداد",
        tracking: "الحركة ظاهرة",
        lost: "عدّل موضعك أمام الكاميرا",
        lostNote: "العدّ ينتظر ظهور المفاصل المطلوبة.",
        phaseIdle: "استعد للحركة",
        phaseLifting: "صعود",
        phaseTop: "أعلى الحركة",
        phaseLowering: "عودة بتحكّم",
        simulated: "محاكاة",
        calibrated: "تم تحديد مداك",
        calStart: "تحرّك ببطء ضمن مداك المريح",
        trainingStart: "لنبدأ مجموعتك",
        savePrivate: "محفوظ في حسابك",
        duration: "مدة التكرار",
        yourReview: "مراجعة الحركة",
      }
    : {
        coachSettings: "A voice that fits you",
        voiceSwitch: "Coach voice",
        voiceSwitchNote: "Guidance and counts during your workout. Captions stay on.",
        preview: "Hear your coach",
        voiceChoice: "Choose a voice",
        close: "Done",
        voiceNote: "Voice generated by AI, packaged inside the app.",
        voiceBlocked: "Audio could not play. Try again; captions remain available.",
        personalize: "Personalize your coach",
        step: "Step",
        next: "Next",
        side: "Side view",
        timeline: "Your set, rep by rep",
        demoTimeline: "Simulated repetitions",
        noneYet: "Your repetitions appear here as the set progresses.",
        complete: "Complete",
        adjust: "With a cue",
        partial: "Shorter range",
        seconds: "s",
        range: "of your personal range",
        rep: "Repetition",
        review: "Explore your movement",
        insight: "What happened in this set?",
        insightGood: "The recorded repetitions completed without compensation flags from tracking.",
        insightAdjust: "Some repetitions had movement flags. Select a rep to review its range and timing.",
        insightPartial:
          "Some movements did not reach the counting range established by calibration. They appear separately from completed reps.",
        insightEmpty: "No repetitions recorded yet. Review your camera position and try again.",
        completed: "Completed reps",
        recent: "Recent sessions",
        export: "Download my record",
        exportNote: "A file of session numbers only. No images or video.",
        resume: "Repeat your last exercise",
        continue: "Use this setup",
        tracking: "Movement in view",
        lost: "Adjust your camera position",
        lostNote: "Counting waits until the required joints are visible.",
        phaseIdle: "Ready for movement",
        phaseLifting: "Lifting",
        phaseTop: "Top of movement",
        phaseLowering: "Controlled return",
        simulated: "Simulation",
        calibrated: "Your range is ready",
        calStart: "Move slowly within your comfortable range",
        trainingStart: "Let’s begin your set",
        savePrivate: "Saved to your account",
        duration: "Rep duration",
        yourReview: "Movement review",
      };
export function insight(reps: { valid: number; compensated: number; partial: number }, lang: Lang) {
  const c = ui(lang);
  return reps.partial
    ? c.insightPartial
    : reps.compensated
      ? c.insightAdjust
      : reps.valid
        ? c.insightGood
        : c.insightEmpty;
}
