import { Lang } from './i18n';
import { RepClass } from '../engine/types';
export interface Preferences { voice: 'full'|'essential'|'off'; pace: number; focus: boolean }
export const defaults: Preferences = {voice:'full',pace:1,focus:false};
export function readPreferences(): Preferences {
 try {const p=JSON.parse(localStorage.getItem('azm.coach')??'{}');return {voice:['full','essential','off'].includes(p.voice)?p.voice:'full',pace:[.85,1,1.15].includes(p.pace)?p.pace:1,focus:p.focus===true};}catch{return {...defaults};}
}
export function savePreferences(p:Preferences) {try{localStorage.setItem('azm.coach',JSON.stringify(p));}catch{/* Settings still work for this visit. */}}
export type RepMoment = {cls:RepClass;durSec:number;peakPct:number};
export const ui = (lang:Lang) => lang==='ar'?{
 coachSettings:'صوت يناسبك',settingsIntro:'اختر مقدار الكلام وسرعته. تبقى الإرشادات مكتوبة دائمًا.', full:'إرشاد وعدّ',essential:'الإرشادات فقط',off:'نص فقط',pace:'سرعة الصوت',slow:'هادئ',normal:'طبيعي',quick:'أسرع',preview:'استمع إلى عزم',close:'تم',voiceNote:'صوت عربي مولّد بالذكاء الاصطناعي، محفوظ داخل التطبيق.',voiceBlocked:'لم يعمل الصوت. حاول مرة أخرى؛ التعليمات النصية متاحة.',
 personalize:'خصّص مدرّبك',walkthrough:'تعرّف على الحركة',listen:'استمع للإرشاد',step:'الخطوة',next:'التالي',previous:'السابق',view:'موضع الكاميرا',front:'مواجهة الكاميرا',side:'من الجانب',angle:'بزاوية',distance:'المسافة',focus:'وضع التركيز',standard:'العرض الكامل',focusNote:'الحركة والملاحظة الحالية فقط',
 timeline:'حركتك، تكرارًا بتكرار',demoTimeline:'تكرارات المحاكاة',noneYet:'تظهر التكرارات هنا مع تقدّم المجموعة.',complete:'مكتمل',adjust:'مع ملاحظة',partial:'مدى أقصر',seconds:'ث',range:'من مداك الشخصي',rep:'التكرار',review:'اقرأ تفاصيل الحركة',
 insight:'ما الذي حدث في هذه المجموعة؟',insightGood:'اكتملت التكرارات المسجّلة دون ملاحظات تعويضية من التتبّع.',insightAdjust:'ظهرت ملاحظات حركة في بعض التكرارات. اختر تكرارًا لمراجعة مداه ووقته.',insightPartial:'بعض الحركات لم تصل إلى مدى العدّ المحدّد بمعايرتك. تُعرض منفصلة عن التكرارات المكتملة.',insightEmpty:'لم تُسجّل تكرارات بعد. يمكنك مراجعة وضع الكاميرا وإعادة المحاولة.',
 sessions:'مجموعات مسجّلة',completed:'تكرارات مكتملة',minutes:'دقائق مسجّلة',recent:'آخر الجلسات',export:'تنزيل سجلّي',exportNote:'ملف يحتوي على أرقام جلساتك فقط، دون صور أو فيديو.',resume:'كرّر آخر تمرين',continue:'تابع بنفس الإعداد',tracking:'الحركة ظاهرة',lost:'عدّل موضعك أمام الكاميرا',lostNote:'العدّ ينتظر ظهور المفاصل المطلوبة.',phaseIdle:'استعد للحركة',phaseLifting:'صعود',phaseTop:'أعلى الحركة',phaseLowering:'عودة بتحكّم',simulated:'محاكاة',calibrated:'تم تحديد مداك',calStart:'تحرّك ببطء ضمن مداك المريح',trainingStart:'لنبدأ مجموعتك',savePrivate:'محفوظ في حسابك',duration:'مدة التكرار',yourReview:'مراجعة الحركة',
 }: {
 coachSettings:'A voice that fits you',settingsIntro:'Choose how much your coach speaks, and at what pace. Captions stay on.',full:'Guidance + counts',essential:'Guidance only',off:'Captions only',pace:'Speaking pace',slow:'Calm',normal:'Natural',quick:'Quicker',preview:'Hear your coach',close:'Done',voiceNote:'AI-generated voice, packaged inside the app.',voiceBlocked:'Audio could not play. Try again; captions remain available.',
 personalize:'Personalize your coach',walkthrough:'Learn the movement',listen:'Listen to this step',step:'Step',next:'Next',previous:'Previous',view:'Camera position',front:'Facing you',side:'Side view',angle:'Angled view',distance:'Distance',focus:'Focus view',standard:'Full view',focusNote:'Movement and the cue that matters now',
 timeline:'Your set, rep by rep',demoTimeline:'Simulated repetitions',noneYet:'Your repetitions appear here as the set progresses.',complete:'Complete',adjust:'With a cue',partial:'Shorter range',seconds:'s',range:'of your personal range',rep:'Repetition',review:'Explore your movement',
 insight:'What happened in this set?',insightGood:'The recorded repetitions completed without compensation flags from tracking.',insightAdjust:'Some repetitions had movement flags. Select a rep to review its range and timing.',insightPartial:'Some movements did not reach the counting range established by calibration. They appear separately from completed reps.',insightEmpty:'No repetitions recorded yet. Review your camera position and try again.',
 sessions:'Recorded sets',completed:'Completed reps',minutes:'Recorded minutes',recent:'Recent sessions',export:'Download my record',exportNote:'A file of session numbers only. No images or video.',resume:'Repeat your last exercise',continue:'Use this setup',tracking:'Movement in view',lost:'Adjust your camera position',lostNote:'Counting waits until the required joints are visible.',phaseIdle:'Ready for movement',phaseLifting:'Lifting',phaseTop:'Top of movement',phaseLowering:'Controlled return',simulated:'Simulation',calibrated:'Your range is ready',calStart:'Move slowly within your comfortable range',trainingStart:'Let’s begin your set',savePrivate:'Saved to your account',duration:'Rep duration',yourReview:'Movement review',
 };
export function insight(reps:{valid:number;compensated:number;partial:number},lang:Lang) {const c=ui(lang);return reps.partial?c.insightPartial:reps.compensated?c.insightAdjust:reps.valid?c.insightGood:c.insightEmpty;}
export const movementSteps:Record<string,{ar:string[];en:string[]}>={
 seated_shoulder_press:{ar:['ابدأ وذراعاك عند مستوى الكتفين، واجعل جذعك ثابتًا.','ارفع ذراعيك فوق الرأس ضمن المدى المريح لك.','أعد ذراعيك إلى مستوى الكتفين بهدوء وتحكّم.'],en:['Begin with your arms at shoulder level and your trunk steady.','Press your arms overhead within your comfortable range.','Return your arms to shoulder level with a controlled movement.']},
 seated_biceps_curl:{ar:['ابدأ والمرفق بجانب جسمك. وجّه جانبك إلى الكاميرا.','اثنِ مرفقك وارفع الوزن نحو كتفك ضمن مداك المريح.','أنزل الوزن ببطء، مع إبقاء المرفق بجانب جسمك.'],en:['Start with your elbow by your side. Turn sideways to the camera.','Bend your elbow, bringing the weight toward your shoulder within your comfortable range.','Lower slowly, keeping your elbow beside your body.']},
 sit_to_stand:{ar:['ابدأ جالسًا، بحيث تُظهر الكاميرا جسمك كاملًا.','انهض من الكرسي حتى تصل إلى وضع الوقوف المريح لك.','عُد إلى الجلوس ببطء وتحكّم.'],en:['Begin seated, with your whole body visible to the camera.','Rise from the chair to your comfortable standing position.','Return to sitting slowly and with control.']},
};
