import { useState } from 'react';
import { Intake,conditions,painOptions,restrictionOptions,validateIntake,Plan } from '../medical/plan';
import { Lang,fmtNum } from './i18n';
import { labels,optionNames,errorText } from './platform-copy';
import { api } from './api';
import Icon from './Icon';
type Draft=Omit<Intake,'symptoms'|'recentChange'|'clearance'|'mobility'> & {symptoms:Intake['symptoms']|'';recentChange:Intake['recentChange']|'';clearance:Intake['clearance']|'';mobility:Intake['mobility']|''};
const empty:Draft={age:0,conditions:[],diagnosisNotes:'',medications:'',mobility:'',support:'none',pain:[],restrictions:[],symptoms:'',recentChange:'',clearance:'',equipment:[],goal:'mobility',days:[0,2,4],time:'09:00',sessionMinutes:30,consent:false};
export default function IntakeForm({lang,initial,onSaved,onCancel}:{lang:Lang;initial:Intake|null;onSaved:(v:{intake:Intake;plan:Plan})=>void;onCancel?:()=>void}){
 const c=labels(lang),[draft,setDraft]=useState<Draft>(initial??empty),[step,setStep]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const set=<K extends keyof Draft>(k:K,v:Draft[K])=>setDraft(d=>({...d,[k]:v}));
 const name=(s:string)=>optionNames[s]?.[lang]??s;
 const toggle=(field:'conditions'|'pain'|'restrictions'|'equipment',v:string)=>{const values=draft[field];set(field,field==='conditions'&&v==='none'?['none']:values.includes(v)?values.filter(x=>x!==v):[...values.filter(x=>x!=='none'),v]);};
 const choices=(field:'conditions'|'pain'|'restrictions'|'equipment',options:readonly string[])=> <div className={`intake-choices ${field==='conditions'?'conditions-grid':''}`}>{options.map(o=><button type="button" key={o} aria-pressed={draft[field].includes(o)} className={draft[field].includes(o)?'selected':''} onClick={()=>toggle(field,o)}><span className="choice-check">{draft[field].includes(o)&&<Icon name="check" size={12}/>}</span>{name(o)}</button>)}{['pain','restrictions'].includes(field)&&<button type="button" className={!draft[field].length?'selected':''} aria-pressed={!draft[field].length} onClick={()=>set(field,[])}>{c.noItems}</button>}</div>;
 const answer=(field:'symptoms'|'recentChange'|'clearance',title:string)=> <label className="intake-question"><span>{title}</span><select required value={draft[field]} onChange={e=>set(field,e.target.value as never)}><option value="">{c.choose}</option><option value="yes">{c.yes}</option><option value="no">{c.no}</option>{field==='clearance'&&<option value="unsure">{c.unsure}</option>}</select></label>;
 const valid=step===0?draft.age>=18&&draft.age<=100&&draft.conditions.length>0:step===1?!!draft.mobility&&!!draft.symptoms&&!!draft.recentChange&&!!draft.clearance:step===2?draft.days.length>0&&draft.days.length<=4:validateIntake(draft);
 const submit=async()=>{if(!valid){setError('INTAKE_INVALID');return;}setError('');if(step<3){setStep(step+1);window.scrollTo(0,0);return;}setBusy(true);try{onSaved(await api('/intake',draft,'PUT'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const weekdays=Array.from({length:7},(_,i)=>new Intl.DateTimeFormat(lang==='ar'?'ar-SA':'en-GB',{weekday:'short'}).format(new Date(2026,8,6+i)));
 return <div className="intake-layout"><aside className="intake-progress"><p className="section-kicker">{c.health}</p><h1>{c.intakeTitle}</h1><p>{c.intakeBody}</p><ol>{c.steps.map((s,i)=><li key={s} className={i===step?'current':i<step?'done':''}><button onClick={()=>i<step&&setStep(i)} disabled={i>step}><b>{i<step?<Icon name="check" size={16}/>:fmtNum(i+1,lang)}</b>{s}</button></li>)}</ol></aside>
 <form className="intake-card" onSubmit={e=>{e.preventDefault();void submit();}}><p className="section-kicker">{fmtNum(step+1,lang)} / {fmtNum(4,lang)}</p><h2>{c.steps[step]}</h2>
 {step===0&&<><label className="field age-field"><span>{c.age}</span><input type="number" inputMode="numeric" min="18" max="100" required value={draft.age||''} onChange={e=>set('age',Number(e.target.value))}/></label><fieldset><legend>{c.condition}</legend><p className="field-help">{c.conditionHelp}</p>{choices('conditions',conditions)}</fieldset><label className="field"><span>{c.diagnosis} <small>{c.optional}</small></span><textarea rows={3} maxLength={1200} value={draft.diagnosisNotes} onChange={e=>set('diagnosisNotes',e.target.value)}/></label><label className="field"><span>{c.medications} <small>{c.optional}</small></span><textarea rows={2} maxLength={1200} value={draft.medications} onChange={e=>set('medications',e.target.value)}/></label></>}
 {step===1&&<><label className="field"><span>{c.mobility}</span><select required value={draft.mobility} onChange={e=>set('mobility',e.target.value as never)}><option value="">{c.choose}</option>{['seated','wheelchair','standing','bed'].map(o=><option key={o} value={o}>{name(o)}</option>)}</select></label><label className="field"><span>{c.support}</span><select value={draft.support} onChange={e=>set('support',e.target.value as never)}><option value="none">{c.noItems}</option>{['left','right'].map(o=><option key={o} value={o}>{name(o)}</option>)}</select></label><fieldset><legend>{c.pain}</legend>{choices('pain',painOptions)}</fieldset><fieldset><legend>{c.restriction}</legend>{choices('restrictions',restrictionOptions)}</fieldset>{answer('symptoms',c.symptoms)}{answer('recentChange',c.recentChange)}{answer('clearance',c.clearance)}</>}
 {step===2&&<><fieldset><legend>{c.equipment}</legend>{choices('equipment',['chair','weights'])}</fieldset><label className="field"><span>{c.goal}</span><select value={draft.goal} onChange={e=>set('goal',e.target.value as never)}>{['mobility','strength','habit'].map(o=><option key={o} value={o}>{name(o)}</option>)}</select></label><fieldset><legend>{c.days}</legend><div className="day-picker">{weekdays.map((day,i)=><button type="button" key={i} aria-pressed={draft.days.includes(i)} className={draft.days.includes(i)?'selected':''} onClick={()=>set('days',draft.days.includes(i)?draft.days.filter(x=>x!==i):draft.days.length<4?[...draft.days,i]:draft.days)}>{day}</button>)}</div></fieldset><div className="field-pair"><label className="field"><span>{c.time}</span><input type="time" required value={draft.time} onChange={e=>set('time',e.target.value)}/></label><label className="field"><span>{c.duration}</span><select value={draft.sessionMinutes} onChange={e=>set('sessionMinutes',Number(e.target.value))}>{[20,30,40].map(n=><option value={n} key={n}>{fmtNum(n,lang)} {c.minutes}</option>)}</select></label></div></>}
 {step===3&&<><h3>{c.reviewTitle}</h3><p className="field-help">{c.reviewBody}</p><dl className="intake-review">{[[c.age,fmtNum(draft.age,lang)],[c.condition,draft.conditions.map(name).join('، ')],[c.mobility,name(draft.mobility)],[c.pain,draft.pain.map(name).join('، ')||c.noItems],[c.restriction,draft.restrictions.map(name).join('، ')||c.noItems],[c.symptoms,draft.symptoms==='yes'?c.yes:c.no],[c.clearance,draft.clearance==='yes'?c.yes:draft.clearance==='no'?c.no:c.unsure],[c.goal,name(draft.goal)],[c.days,[...draft.days].sort().map(i=>weekdays[i]).join(' · ')],[c.time,draft.time]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><label className="consent"><input type="checkbox" required checked={draft.consent} onChange={e=>set('consent',e.target.checked)}/><span>{c.consent}</span></label></>}
 {error&&<p className="form-error" role="alert">{errorText(error,lang)}</p>}<div className="intake-actions"><button className="cta" disabled={busy} type="submit">{busy?c.busy:step===3?(initial?c.save:c.create):c.continue}<Icon name="arrow" size={18}/></button>{step>0?<button type="button" className="ghost" onClick={()=>setStep(step-1)}>{c.back}</button>:onCancel&&<button type="button" className="ghost" onClick={onCancel}>{c.back}</button>}</div></form></div>;
}
