import { Lang } from "./i18n";
export const labels = (l: Lang) =>
  l === "ar"
    ? {
        login: "تسجيل الدخول",
        register: "إنشاء حساب",
        name: "الاسم",
        email: "البريد الإلكتروني",
        password: "كلمة المرور",
        passwordHint: "10 أحرف على الأقل",
        authTitle: "خطتك تبدأ\nمن حالتك الطبية.",
        authBody: "نتعرّف على حالتك وقدرتك على الحركة، ثم نبني برنامجك ونرشدك خلاله.",
        authFoot: "يحفظ حسابك برنامجك ونتائجك.",
        demo: "استكشف جلسة تجريبية",
        welcome: "أهلًا",
        today: "اليوم",
        program: "البرنامج",
        health: "حالتك الطبية",
        // D-018: the tabs; the page titles keep the full names.
        nav: { today: "اليوم", program: "برنامجي", health: "حالتي" },
        titles: { today: "اليوم", program: "برنامجي", health: "حالتي الطبية" },
        logout: "تسجيل الخروج",
        backHome: "العودة للرئيسية",
        continue: "متابعة",
        back: "رجوع",
        save: "حفظ وتحديث البرنامج",
        create: "أنشئ برنامجي",
        edit: "تعديل الملف",
        loading: "جارٍ التحميل…",
        busy: "لحظة من فضلك…",
        intakeTitle: "لنبدأ بما يهمّك.",
        intakeBody: "إجاباتك تحدّد التمارين المتاحة، عدد المجموعات، وفترات الراحة.",
        steps: ["حالتك الطبية", "الحركة والاحتياطات", "هدفك ووقتك", "المراجعة"],
        age: "العمر",
        condition: "ما حالتك الطبية؟",
        conditionHelp: "اختر كل ما ينطبق عليك.",
        diagnosis: "تفاصيل التشخيص أو تعليمات الطبيب",
        medications: "الأدوية الحالية",
        optional: "اختياري",
        // D-035 item 5: a position question, so someone who does not exercise yet can answer it.
        mobility: "ما الوضعية الأنسب لك في التمرين؟",
        support: "هل يحتاج أحد جانبي جسمك إلى مراعاة خاصة؟",
        pain: "هل تؤلمك إحدى هذه المناطق عند الحركة؟",
        restriction: "هل لديك تعليمات طبية تحدّ من حركتك؟",
        noItems: "لا شيء مما سبق",
        symptoms: "هل لديك ألم صدر، إغماء، أو ضيق تنفّس غير معتاد مع الجهد؟",
        recentChange: "هل طرأ تدهور حديث، إصابة جديدة، أو جراحة لم يسمح بعدها الطبيب بالعودة للتمرين؟",
        clearance: "هل سمح لك الطبيب بممارسة التمرين؟",
        yes: "نعم",
        no: "لا",
        unsure: "غير متأكد",
        choose: "اختر إجابة",
        equipment: "ما الأدوات المتاحة لديك؟",
        equipmentHelp: "يكفيك كرسي ثابت للبدء. اختر ما لديك غيره.",
        goal: "ما هدفك؟",
        sportPick: "اختر رياضتك",
        days: "أيام التمرين المفضّلة",
        time: "وقت التمرين",
        duration: "الوقت المتاح للجلسة",
        minutes: "دقيقة",
        consent: "أوافق على حفظ إجاباتي الصحية في حسابي لاستخدامها في إعداد البرنامج.",
        reviewTitle: "راجع إجاباتك قبل أن نبدأ.",
        reviewBody: "يمكنك تعديلها في أي وقت. أي تغيير يعيد تقييم البرنامج.",
        schedule: "أسبوعك القادم",
        nextSession: "جلستك القادمة",
        start: "ابدأ الجلسة",
        preview: "شاهد عرضًا توضيحيًا",
        viewPlan: "تفاصيل البرنامج",
        restDay: "يوم راحة",
        workoutDay: "موعد تمرين",
        planReady: "برنامجك جاهز",
        planReview: "نحتاج إلى مراجعة قبل التمرين",
        planReviewBody: "لم نُفعّل التدريب بسبب المعلومات التالية. راجع مختصّك، ثم حدّث إجاباتك إن تغيّرت.",
        reasons: "لماذا هذا البرنامج؟",
        excluded: "تمارين لم نُدرجها",
        sets: "مجموعات",
        reps: "تكرارات",
        rest: "راحة",
        seconds: "ثانية",
        warmup: "الإحماء",
        cooldown: "التهدئة",
        warmupBody: "ابدأ بالإحماء المعتاد الذي تعرفه أو أوصى به مختصّك. تحرّك بهدوء ضمن مداك المريح.",
        cooldownBody: "انتهى التدريب. خذ وقتك للعودة إلى الراحة، دون استعجال.",
        ready: "أنا جاهز",
        attest: "لم تتغير حالتي الطبية منذ آخر إجاباتي، ولا أشعر بأعراض جديدة.",
        showSteps: "اعرض خطوات التجهيز",
        startTraining: "ابدأ التمرين",
        highEffort: "جهدك مرتفع. انتهِ لليوم وخذ راحتك.",
        nextSet: "المجموعة التالية",
        finish: "إنهاء الجلسة",
        restTitle: "خذ وقتك بين المجموعات.",
        restBody: "تأتي المجموعة التالية بعد الراحة، ويمكنك أخذ وقت أطول إذا احتجت.",
        nextExercise: "التالي",
        set: "المجموعة",
        of: "من",
        done: "انتهت جلستك",
        doneBody: "يمكنك مراجعة ما أنجزته في نتائجي.",
        demoDone: "انتهت المحاكاة؛ لم تُضف إلى سجلك.",
        exit: "العودة للبرنامج",
        saveError: "لم نتمكّن من حفظ المجموعة. حاول مجددًا قبل المتابعة.",
        retry: "إعادة المحاولة",
        reported: "ما أخبرتنا به",
        recordNote: "إقرار السماح الطبي صادر منك، وليس تحققًا من تقرير الطبيب.",
        session: "جلسة",
        calendar: "الأيام",
        neural: "صوت المدرّب",
        resume: "متابعة الجلسة",
        signOutError: "تعذّر الخروج. حاول مرة أخرى.",
        reportTitle: "عندك تقرير طبي؟",
        // D-035 item 5: the card that opens the report reading in a v7 form.
        reportCardLine: "ارفع تقريرك الطبي، ونقرأه لك ونملأ حالتك",
        reportBody: "صوّر صفحة التقرير أو الصق نصه، فنعبّئ منه إجاباتك مسبقًا، ثم نسألك عمّا تبقّى فقط.",
        // Booth v2 (B8, option A): one plain line; pressing «اقرأ تقريري» is the consent.
        reportNotice: "يقرأ عزم تقريرك مرة واحدة ليملأ إجاباتك، ولا يحتفظ به.",
        reportRead: "اقرأ تقريري",
        reportPasteOpen: "أو الصق نص التقرير",
        reportPhotoOpen: "أو صوّر التقرير",
        reportPaste: "نص التقرير",
        reportBusy: "يقرأ عزم تقريرك…",
        reportSkip: "تخطَّ وأجب يدويًا",
        reportDone: "استخرجنا هذه المعلومات من تقريرك، تأكّد منها قبل المتابعة.",
        reportMissing: "يتبقى عليك الإجابة عن:",
        reportBadge: "من التقرير",
        reportNotMedical: "لم نتعرّف على تقرير طبي في الملف. أكمل الإجابات يدويًا.",
      }
    : {
        login: "Sign in",
        register: "Create account",
        name: "Name",
        email: "Email address",
        password: "Password",
        passwordHint: "At least 10 characters",
        authTitle: "Your plan starts\nwith your medical condition.",
        authBody:
          "Start with your health and how you move. Build your program, then follow it with guidance.",
        authFoot: "Your account keeps your program and your results.",
        demo: "Explore a demo session",
        welcome: "Welcome",
        today: "Today",
        program: "Program",
        health: "Your medical condition",
        // D-018: the tabs; the page titles keep the full names.
        nav: { today: "Today", program: "Program", health: "My condition" },
        titles: { today: "Today", program: "My program", health: "My medical condition" },
        logout: "Sign out",
        backHome: "Back to home",
        continue: "Continue",
        back: "Back",
        save: "Save & update program",
        create: "Build my program",
        edit: "Edit profile",
        loading: "Loading…",
        busy: "One moment…",
        intakeTitle: "Start with what matters.",
        intakeBody: "Your answers shape the exercises, sets and recovery in your program.",
        steps: ["Your medical condition", "Movement and precautions", "Goals and schedule", "Review"],
        age: "Age",
        condition: "Which conditions apply to you?",
        conditionHelp: "Select all that apply.",
        diagnosis: "Diagnosis details or clinician instructions",
        medications: "Current medications",
        optional: "Optional",
        mobility: "Which position suits you best for exercise?",
        support: "Should we account for one side?",
        pain: "Do any of these areas hurt during movement?",
        restriction: "Do you have any movement restrictions?",
        noItems: "None of these",
        symptoms: "Do you have chest pain, fainting, or unusual breathlessness with exertion?",
        recentChange:
          "Any recent deterioration, new injury, or surgery without permission to return to exercise?",
        clearance: "Has your doctor cleared you to exercise?",
        yes: "Yes",
        no: "No",
        unsure: "Not sure",
        choose: "Choose an answer",
        equipment: "What equipment do you have?",
        equipmentHelp: "A stable chair is all you need to start. Add anything else you have.",
        goal: "What is your goal?",
        sportPick: "Choose your sport",
        days: "Preferred training days",
        time: "Training time",
        duration: "Time available per session",
        minutes: "minutes",
        consent: "I agree to store my health answers in my account to prepare my program.",
        reviewTitle: "Review your starting point.",
        reviewBody: "You can update this anytime. Changes trigger a new program assessment.",
        schedule: "Your coming week",
        nextSession: "Your next session",
        start: "Start session",
        preview: "Watch a demo",
        viewPlan: "Explore program",
        restDay: "Rest day",
        workoutDay: "Training day",
        planReady: "Your program is ready",
        planReview: "Review needed before training",
        planReviewBody:
          "Training is not enabled for the reasons below. Review these with your clinician, then update your answers if they change.",
        reasons: "Why this program?",
        excluded: "Exercises not included",
        sets: "sets",
        reps: "reps",
        rest: "rest",
        seconds: "seconds",
        warmup: "Warm up",
        cooldown: "Wind down",
        warmupBody:
          "Use your familiar warm up or the one your clinician has advised. Move gently within your comfortable range.",
        cooldownBody: "Your training is finished. Take time to return to rest, without rushing.",
        ready: "I’m ready",
        attest: "My medical condition has not changed since my last answers, and I have no new symptoms.",
        showSteps: "Show the setup steps",
        startTraining: "Start training",
        highEffort: "Your effort was high. Finish for today and take time to rest.",
        nextSet: "Next set",
        finish: "Finish session",
        restTitle: "Take a moment between sets.",
        restBody: "Your next set follows this rest. You can take longer if you need.",
        nextExercise: "Up next",
        set: "Set",
        of: "of",
        done: "Your session is complete",
        doneBody: "Review your recorded movements in My results.",
        demoDone: "Simulation complete. It was not added to your history.",
        exit: "Back to program",
        saveError: "We could not save this set. Retry before continuing.",
        retry: "Try again",
        reported: "What you told us",
        recordNote: "Medical clearance is self reported, not verification of a clinician’s report.",
        session: "session",
        calendar: "Days",
        neural: "Coach voice",
        resume: "Resume session",
        signOutError: "Could not sign out. Please try again.",
        reportTitle: "Have a medical report?",
        reportCardLine: "Upload your medical report, we read it and fill in your condition",
        reportBody:
          "Photograph the report page or paste its text. We prefill your answers from it, then ask only what is still missing.",
        // Booth v2 (B8, option A): one plain line; pressing Read my report is the consent.
        reportNotice: "Azm reads your report once to fill in your answers, and does not keep it.",
        reportRead: "Read my report",
        reportPasteOpen: "Or paste the report text",
        reportPhotoOpen: "Or photograph the report",
        reportPaste: "Report text",
        reportBusy: "Azm is reading your report…",
        reportSkip: "Skip and answer manually",
        reportDone: "We extracted this from your report. Please verify before continuing.",
        reportMissing: "Still to answer:",
        reportBadge: "from report",
        reportNotMedical: "We could not recognize a medical report in this file. Please answer manually.",
      };
export const optionNames: Record<string, { ar: string; en: string }> = {
  // The condition labels are the check's person first wording (S08 guest chips use these exactly).
  none: { ar: "لا شيء مما سبق", en: "None of these" },
  stroke: { ar: "سكتة دماغية", en: "Stroke" },
  ms: { ar: "التصلب المتعدد", en: "Multiple sclerosis" },
  cerebral_palsy: { ar: "الشلل الدماغي", en: "Cerebral palsy" },
  sci_complete: { ar: "إصابة كاملة في الحبل الشوكي", en: "Complete spinal cord injury" },
  sci_incomplete: { ar: "إصابة غير كاملة في الحبل الشوكي", en: "Incomplete spinal cord injury" },
  parkinsons: { ar: "مرض باركنسون", en: "Parkinson’s" },
  lower_limb_unilateral: { ar: "فقدان ساق واحدة أو جزء منها", en: "Loss of all or part of one leg" },
  upper_limb_unilateral: { ar: "فقدان ذراع واحدة أو جزء منها", en: "Loss of all or part of one arm" },
  arthritis: { ar: "التهاب المفاصل", en: "Arthritis" },
  cfs_moderate: { ar: "متلازمة التعب المزمن", en: "Chronic fatigue syndrome" },
  cardiac: { ar: "حالة قلبية", en: "A heart condition" },
  other: { ar: "حالة أخرى غير مذكورة هنا", en: "Another condition not listed here" },
  seated: { ar: "جالسًا على كرسي", en: "Seated on a chair" },
  wheelchair: { ar: "بكرسي متحرك", en: "Using a wheelchair" },
  standing: {
    ar: "يمكنني التمرّن واقفًا والنهوض من كرسي",
    en: "I can exercise standing and rise from a chair",
  },
  bed: { ar: "على السرير / أحتاج دعمًا مستمرًا", en: "In bed / continuous support" },
  left: { ar: "الجانب الأيسر", en: "Left side" },
  right: { ar: "الجانب الأيمن", en: "Right side" },
  shoulder: { ar: "الكتف", en: "Shoulder" },
  elbow: { ar: "المرفق", en: "Elbow" },
  wrist: { ar: "المعصم", en: "Wrist" },
  back: { ar: "الظهر", en: "Back" },
  hip: { ar: "الورك", en: "Hip" },
  knee: { ar: "الركبة", en: "Knee" },
  no_overhead: { ar: "تجنّب رفع الذراعين فوق الرأس", en: "Avoid overhead movement" },
  no_resistance: { ar: "تجنّب الأوزان والمقاومة", en: "Avoid weights / resistance" },
  no_weight_bearing: { ar: "تجنّب تحميل الوزن على الساقين", en: "Avoid weight bearing through legs" },
  no_exercise: { ar: "أوصاني الطبيب بعدم التمرّن حاليًا", en: "Advised not to exercise currently" },
  balance_support: { ar: "أحتاج مساعدة للوقوف والتوازن", en: "I need help to stand / balance" },
  chair: { ar: "كرسي ثابت", en: "Stable chair" },
  weights: { ar: "أوزان مناسبة أستخدمها بالفعل", en: "Suitable weights I already use" },
  bands: { ar: "أشرطة مقاومة", en: "Resistance bands" },
  mobility: { ar: "الحركة اليومية", en: "Everyday movement" },
  strength: { ar: "القوة والتحكّم", en: "Strength & control" },
  habit: { ar: "الانتظام في التمرين", en: "Build a routine" },
  sport: { ar: "العودة إلى الرياضة", en: "Back to sport" },
};
export const reasonText: Record<string, { ar: string; en: string }> = {
  cardiac: {
    ar: "الحالات القلبية خارج نطاق التدريب التلقائي في عزم. يلزم برنامج بإشراف مختص.",
    en: "Cardiac conditions are outside Azm’s automatic training scope. A program supervised by a specialist is needed.",
  },
  symptoms: {
    ar: "الأعراض المذكورة تستدعي تقييمًا طبيًا قبل التدريب. إذا كانت تحدث الآن، اطلب مساعدة طبية عاجلة.",
    en: "The reported symptoms need medical assessment before training. If they are happening now, seek urgent medical help.",
  },
  recent_change: {
    ar: "التغيّر الصحي الحديث يحتاج مراجعة قبل العودة للتمرين.",
    en: "The recent health change needs review before returning to exercise.",
  },
  restriction: {
    ar: "أشرت إلى وجود تعليمات بعدم التمرّن حاليًا.",
    en: "You reported advice not to exercise at present.",
  },
  unknown_condition: {
    ar: "الحالة غير المدرجة تحتاج مراجعة؛ لن نخمن برنامجًا لها.",
    en: "An unlisted condition needs review before a program can be prepared.",
  },
  clearance: {
    ar: "إعدادات حالتك تتطلب السماح الطبي قبل بدء البرنامج.",
    en: "Your condition settings require medical clearance before starting.",
  },
  pem: {
    ar: "التعب المتأخر بعد الجهد يحتاج خطة فردية لموازنة النشاط والراحة؛ لن نولّد له جرعة تمرين ثابتة.",
    en: "Symptoms that worsen after exertion need individualized activity management. A fixed exercise dose will not be generated.",
  },
  unsupported_position: {
    ar: "التمارين المتاحة حاليًا لا تغطي التدريب على السرير أو الدعم المستمر.",
    en: "The current exercises do not cover training in bed or continuous support.",
  },
  recovery: {
    ar: "باعد بين أيام التمرين لتستوفي فترة التعافي المطلوبة، بما فيها نهاية الأسبوع.",
    en: "Space training days to meet the recovery interval, including across the end of the week.",
  },
  duration: {
    ar: "الوقت الذي اخترته لا يتّسع للتهيئة والتدريب والراحة. اختر وقتًا أطول أو راجع مختصّك.",
    en: "Your selected time does not fit preparation, training and recovery. Choose a longer window or review with your clinician.",
  },
  no_exercises: {
    ar: "لا توجد حركة من المكتبة الحالية تجمع شروطك. نحتاج تمرينًا بديلًا يحدّده مختصّك.",
    en: "No exercise in the current library meets all your requirements. An alternative needs your clinician’s input.",
  },
  temperature: {
    ar: "راعِ حرارة المكان وخذ فواصل عند الحاجة؛ إعدادات حالتك تراعي حساسية الحرارة.",
    en: "Account for room temperature and take breaks as needed; your condition settings flag heat sensitivity.",
  },
  fatigue: {
    ar: "خُفّضت جرعة التمرين وزِيدت الراحة وفق إعدادات حالتك.",
    en: "Exercise volume is reduced and rest extended by your condition settings.",
  },
  self_reported_clearance: {
    ar: "السماح الطبي مُبلّغ منك، وليس تقريرًا تحقّقنا منه.",
    en: "Medical clearance is self reported, not a verified report.",
  },
  medications_recorded: {
    ar: "حُفظت الأدوية للمراجعة. لا يحلل هذا البرنامج تداخلاتها أو يغيّر جرعاتها.",
    en: "Medication details are recorded for review. This program does not analyze interactions or change doses.",
  },
  tracking_limbs: {
    ar: "هذه الحركة تتطلب مفاصل لا يمكن للنموذج الحالي تتبّعها في هذا الإعداد.",
    en: "This movement requires joints that the current model cannot track in this setup.",
  },
  pain_upper: {
    ar: "استُبعدت بسبب ألم الجزء العلوي أو الظهر؛ لا نطبّق تعديلًا غير متحقق منه.",
    en: "Excluded for reported upper body or back pain; unsupported modifications are not applied.",
  },
  // v7 (D-029 item 1, E2-8): a recent surgery or injury on the body map.
  region_recent: {
    ar: "استُبعدت بسبب جراحة أو إصابة حديثة ذكرتها في هذه المنطقة.",
    en: "Excluded for a recent surgery or injury you reported in this area.",
  },
  overhead: {
    ar: "لديك تعليمات بتجنّب الحركة فوق الرأس.",
    en: "You reported a restriction on overhead movement.",
  },
  resistance: {
    ar: "المقاومة غير متاحة أو لديك تعليمات بتجنّبها.",
    en: "Suitable resistance is unavailable or restricted.",
  },
  // Plans saved before booth v2 may still name the chair (a stable chair is now assumed).
  chair: { ar: "تتطلب هذه الحركة كرسيًا ثابتًا.", en: "This movement requires a stable chair." },
  curl_unloaded: {
    ar: "تُؤدّى دون أوزان، أو بشيء خفيف في يدك مثل قارورة ماء.",
    en: "Done without weights, or with something light in your hand such as a water bottle.",
  },
  standing: {
    ar: "لم تُدرج بسبب وضعيتك أو ألم الساقين أو متطلبات التوازن والتتبّع.",
    en: "Not included due to position, lower body pain, balance or tracking requirements.",
  },
  seated_match: {
    ar: "حركة تُؤدّى جلوسًا، متوافقة مع الإعداد والقيود التي أدخلتها.",
    en: "A seated movement matching your reported setup and restrictions.",
  },
  standing_match: {
    ar: "أُدرجت لأنك تستطيع النهوض والوقوف دون القيود المستبعدة.",
    en: "Included because you reported being able to rise and stand without the excluded restrictions.",
  },
};
export function errorText(code: string, l: Lang) {
  const m: Record<string, [string, string]> = {
    CREDENTIALS: ["البريد أو كلمة المرور غير صحيحة.", "Email or password is incorrect."],
    CREDENTIAL_FORMAT: [
      "تحقّق من البريد وكلمة المرور (10 أحرف على الأقل).",
      "Check your email and password (at least 10 characters).",
    ],
    ADULT_REQUIRED: [
      "حسابات عزم لمن عمرهم 18 سنة أو أكثر. أكّد عمرك لإنشاء الحساب.",
      "Azm accounts are for people aged 18 or older. Confirm your age to create the account.",
    ],
    ACCOUNT_EXISTS: [
      "يوجد حساب بهذا البريد. سجّل الدخول.",
      "An account already uses this email. Please sign in.",
    ],
    RATE_LIMIT: ["محاولات كثيرة. حاول مجددًا بعد 15 دقيقة.", "Too many attempts. Try again in 15 minutes."],
    INTAKE_INVALID: ["أكمل الإجابات المطلوبة وتحقّق منها.", "Complete and check the required answers."],
    PLAN_CHANGED: [
      "تغيّر ملفك الصحي. عد إلى البرنامج المحدّث.",
      "Your health profile changed. Return to the updated program.",
    ],
    RECOVERY: [
      "لم تنتهِ فترة التعافي منذ آخر جلسة. يمكنك معاينة البرنامج دون تمرين.",
      "Your recovery interval has not elapsed since the last session. You can preview the program.",
    ],
    EXTRACTION_UNAVAILABLE: [
      "محرك تحليل التقارير غير متاح حاليًا. أكمل الإجابات يدويًا.",
      "Report analysis is currently unavailable. Please answer manually.",
    ],
    REPORT_INVALID: [
      "تعذّر قراءة الملف. جرّب صورة أوضح أو الصق النص.",
      "We could not read the file. Try a clearer photo or paste the text.",
    ],
    ENGINE_FAILED: [
      "تعذّر تحليل التقرير. حاول مجددًا أو أكمل يدويًا.",
      "Report analysis failed. Try again or continue manually.",
    ],
  };
  return (m[code] ?? [
    "تعذّر إكمال الطلب. حاول مجددًا.",
    "The request could not be completed. Please try again.",
  ])[l === "ar" ? 0 : 1];
}
