/**
 * Typed access to the v7 runtime gait data (product v7 contract 2.1).
 *
 * src/movements/gait/gait-v7.json is generated by scripts/clinical/export-v7.mjs from the clinical
 * source (C-1): capture numbers, metrics and their grades, norms, error margins, the confidence model,
 * the patterns and the copy of the gait test. The values are signed off (GAIT_DATA.signoff, D-025;
 * version 1.0.0; the engineering defaults stay interim until the GAIT-Q3 tuning). Pure data, no DOM. Imported only by v7 chunks (8.8).
 */
import raw from "./gait-v7.json";
import type { WidenV7 } from "../rom/types";
import type { GaitFindingDef, GaitData, GaitPatternDef } from "./types";
import type { GaitPatternId } from "../../medical/gait-types";

// Compile time shape check; literal ids are checked by tests/v7/a-runtime-data.test.ts.
const checked = raw satisfies WidenV7<GaitData>;

export const GAIT_DATA: GaitData = checked as unknown as GaitData;

/** The rules version stored with the gait findings, for example "gait_rules_1.0.0". */
export const GAIT_RULES_VERSION = `gait_rules_${GAIT_DATA.version}`;
/** The engine's version, stored with every analysis (bumped by stream C when the engine changes). */
export const GAIT_ENGINE_VERSION = "gait_engine_5";

/** One pattern: its views, signs and the numbers of its rules (GAIT_DATA.patterns). */
export function gaitPattern(id: GaitPatternId): GaitPatternDef {
  const p = GAIT_DATA.patterns.find((x) => x.id === id);
  if (!p) throw new Error(`Unknown gait pattern: ${id}`);
  return p;
}

/** One support finding: its views and the thresholds of its rule (GAIT_DATA.findings). */
export function gaitFinding(id: GaitFindingDef["id"]): GaitFindingDef {
  const f = GAIT_DATA.findings.find((x) => x.id === id);
  if (!f) throw new Error(`Unknown gait finding: ${id}`);
  return f;
}
