/**
 * Typed access to the v7 runtime exercise targets data (product v7 contract 2.1 and 2.10).
 *
 * src/movements/targets/targets-v7.json is generated by scripts/clinical/export-v7.mjs from the
 * clinical source (C-1): the target taxonomy, dose profiles, library tags, the new exercises (status
 * draft), the contraindication vocabulary, the mapping from findings to targets and the why lines.
 * Every value is a draft until the clinical sign off (TARGETS_DATA.signoff). Pure data, no DOM.
 * Imported only by v7 chunks (8.8).
 */
import raw from "./targets-v7.json";
import type { WidenV7 } from "../rom/types";
import type { TargetsData } from "./types";

// Compile time shape check; literal ids are checked by tests/v7/a-runtime-data.test.ts.
const checked = raw satisfies WidenV7<TargetsData>;

export const TARGETS_DATA: TargetsData = checked as unknown as TargetsData;

/** The targets version stored with a targeted weekly, for example "targets_0.2.1". */
export const TARGETS_VERSION = `targets_${TARGETS_DATA.version}`;
