/**
 * Typed access to the v7 runtime range of motion data (product v7 contract 2.1).
 *
 * src/movements/rom/rom-v7.json is generated by scripts/clinical/export-v7.mjs from the clinical
 * source (C-1) and is the app's source of truth for the movements, positions, norms, reasons and
 * copy of the range of motion check. Every value is a draft until the clinical sign off
 * (ROM_DATA.signoff). Pure data, no DOM: shared by the client and the server. Imported only by v7
 * chunks (8.8).
 */
import raw from "./rom-v7.json";
import type { RegionId } from "../../medical/body-map";
import type { Text } from "../types";
import type {
  DefaultMovementDef,
  DefaultOnlyId,
  RegionTableRow,
  RomCopyKey,
  RomCueId,
  RomData,
  RomMovementDef,
  RomMovementId,
  RomResultKey,
  WidenV7,
} from "./types";

// Compile time check that the JSON has every field of RomData with the right nesting and primitive
// types. Literal values (ids, kinds, positions) are checked by tests/v7/a-runtime-data.test.ts.
const checked = raw satisfies WidenV7<RomData>;

// Literal unions and tuples are narrower than the JSON's inferred types, so the cast goes through
// unknown; the satisfies check above and the data tests are what make it safe.
export const ROM_DATA: RomData = checked as unknown as RomData;

/** The rules version stored with a protocol and its findings, for example "rom_protocol_0.2.2". */
export const ROM_RULES_VERSION = `rom_protocol_${ROM_DATA.specVersion}`;
/** The norms ship inside the ROM data, so they carry its spec version. */
export const NORMS_VERSION = `rom_norms_${ROM_DATA.specVersion}`;
/** The runner's version, stored with every measurement (bumped by stream B when the runner changes). */
export const ROM_ENGINE_VERSION = "rom_engine_1";

function missing(kind: string, id: string): never {
  throw new Error(`Unknown range of motion ${kind}: ${id}`);
}

const movementsById = new Map(ROM_DATA.movements.map((m) => [m.id, m]));
const defaultsById = new Map(ROM_DATA.defaultMovements.map((m) => [m.id, m]));
const regionRows = new Map(ROM_DATA.regionTable.map((r) => [r.region, r]));

/** The definition of one measured movement. */
export function movementDef(id: RomMovementId): RomMovementDef {
  return movementsById.get(id) ?? missing("movement", id);
}

/** The definition of one default only movement (never measured by the camera). */
export function defaultDef(id: DefaultOnlyId): DefaultMovementDef {
  return defaultsById.get(id) ?? missing("default movement", id);
}

/** The region table row of a body map region: its measure, caution, default, core and extended movements. */
export function regionRow(region: RegionId): RegionTableRow {
  return regionRows.get(region) ?? missing("region", region);
}

/** A copy line of the range of motion check (ROM_DATA.copy). */
export function romCopy(key: RomCopyKey): Text {
  return ROM_DATA.copy[key] ?? missing("copy key", key);
}

/** A correction cue line (ROM_DATA.cues). */
export function romCue(id: RomCueId): Text {
  return ROM_DATA.cues[id] ?? missing("cue", id);
}

/** A result line (ROM_DATA.results). */
export function romResultLine(key: RomResultKey): Text {
  return ROM_DATA.results[key] ?? missing("result line", key);
}
