/**
 * Typed access to the runtime movement check data (contract v2, section A).
 *
 * src/movements/check-v1.json is generated by scripts/clinical/export-check.mjs from the clinical
 * spec and is the app's source of truth for the check: tests, pre-check, screens, reasons, cues,
 * progress wording and selection. Every value is a draft until sign-off (CHECK_DATA.signoff).
 * Pure data, no DOM: shared by the client and the server.
 */
import raw from "./check-v1.json";
import type {
  AfterCheckId,
  BetweenTestId,
  CheckCueId,
  CheckData,
  CueLine,
  EndOfCheckId,
  EndOfCheckQuestion,
  FollowQuestion,
  Lang,
  PausedWhenTokens,
  PrecheckId,
  PrecheckItem,
  QuestionId,
  ReasonId,
  ScreenId,
  SetupQuestion,
  SetupQuestionId,
  StopFollowUp,
  StopFollowUpId,
  TestDefById,
  TestId,
  Widen,
} from "./types";
import { CHECK_CUE_IDS, TEST_ID_LIST } from "./types";

// Compile time check that the JSON has every field of CheckData with the right nesting and
// primitive types. Literal values (ids, kinds, units) are checked by tests/movement-data.test.ts.
const checked = raw satisfies Widen<CheckData>;

// Literal unions and tuples are narrower than the JSON's inferred types, so the cast goes through
// unknown; the satisfies check above and the data tests are what make it safe.
export const CHECK_DATA: CheckData = checked as unknown as CheckData;

/** Test ids in data order (the order of the tests array, not the per position order). */
export const TEST_IDS: readonly TestId[] = CHECK_DATA.tests.map((t) => t.id);

export function isTestId(id: string): id is TestId {
  return (TEST_ID_LIST as readonly string[]).includes(id);
}

export function isCheckCueId(id: string): id is CheckCueId {
  return (CHECK_CUE_IDS as readonly string[]).includes(id);
}

const testsById = new Map(CHECK_DATA.tests.map((t) => [t.id, t]));
const questionsById = new Map<string, PrecheckItem | FollowQuestion>([
  ...CHECK_DATA.precheck.map((q) => [q.id, q] as const),
  ...CHECK_DATA.betweenTests.map((q) => [q.id, q] as const),
  ...CHECK_DATA.afterCheck.map((q) => [q.id, q] as const),
]);
const cuesById = new Map(CHECK_DATA.cues.map((c) => [c.id, c]));

function missing(kind: string, id: string): never {
  throw new Error(`Unknown movement check ${kind}: ${id}`);
}

/** The definition of one test, typed per test id. */
export function testDef<I extends TestId>(id: I): TestDefById[I] {
  return (testsById.get(id) ?? missing("test", id)) as TestDefById[I];
}

/**
 * A question of the check by id: pre-check items (pc_), the between tests question (bt_) and the
 * after check question (ac_), since test exclusions list all three kinds.
 */
export function precheckItem(id: PrecheckId): PrecheckItem;
export function precheckItem<I extends BetweenTestId | AfterCheckId>(id: I): FollowQuestion<I>;
export function precheckItem(id: QuestionId): PrecheckItem | FollowQuestion;
export function precheckItem(id: QuestionId): PrecheckItem | FollowQuestion {
  return questionsById.get(id) ?? missing("question", id);
}

/** Text of a full screen or warning (scr_, warn_), with its {tokens} still in place. */
export function screenText(id: ScreenId, lang: Lang): string {
  return (CHECK_DATA.screens[id] ?? missing("screen", id))[lang];
}

/** Why a test was skipped, changed or stopped, shown with the result (spec 3.6). */
export function reasonText(id: ReasonId, lang: Lang): string {
  return (CHECK_DATA.reasons[id] ?? missing("reason", id))[lang];
}

/** A check voice cue: ar (display), arTts (fully vocalized, for speech) and en. */
export function cueLine(id: CheckCueId): CueLine {
  return cuesById.get(id) ?? missing("cue", id);
}

/* ------------------------------------------------ revision 1.1 sections (O33 (7)) */

/** The faint follow up after a faint or a fall stop (S38b, sf_faint_loc). */
export function stopFollowUp(id: StopFollowUpId): StopFollowUp {
  return CHECK_DATA.stopFollowUps.find((q) => q.id === id) ?? missing("stop follow up", id);
}

/** The end of check symptom question (S49, ec_symptoms): ask, askSide with {side}, sideTokens. */
export function endOfCheckQuestion(id: EndOfCheckId): EndOfCheckQuestion {
  return CHECK_DATA.endOfCheck.find((q) => q.id === id) ?? missing("end of check question", id);
}

/** A chair stand setup question at home (su_chair_gate, su_same_chair; Q9). */
export function setupQuestion(id: SetupQuestionId): SetupQuestion {
  return CHECK_DATA.setupQuestions.find((q) => q.id === id) ?? missing("setup question", id);
}

export type PausedWhenToken = Exclude<keyof PausedWhenTokens, "timeSuffix">;

/** The {when} line of a lock (Q33 (4)), with its {time} token still in place. */
export function pausedWhenText(token: PausedWhenToken, lang: Lang): string {
  return (CHECK_DATA.pausedWhenTokens[token] ?? missing("paused when token", token))[lang];
}

/** The call button of every screen that names 997 (emergencyCall.button, Q22), and its href. */
export function emergencyCallButton(lang: Lang): { label: string; href: string } {
  const b = CHECK_DATA.emergencyCall.button;
  return { label: b[lang], href: b.href };
}
