import {chromium} from '@playwright/test';
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:900,height:560},deviceScaleFactor:10});
await page.goto('http://localhost:5205/?lang=en&demo=1&profile=wheelchair&ex=seated_shoulder_press&autostart=1&fast=1');await page.waitForSelector('.rep-card',{timeout:45000});
await page.addStyleTag({content:`
/* Print-only layout of the working demo; no exercise values or labels changed. */
html,body{width:900px!important;margin:0!important;background:white!important}.session{padding:16px!important;width:900px!important;min-height:0!important;background:#f5f6f8!important;box-sizing:border-box!important}.session-header,.session-steps,.tracking-status,.session-title .eyebrow,.movement-heading,.signal-strip,.rep-review,.demo-reference>span,.coach-heading,.rep-sub,.range-meter,.coach-message p,.step-label,.session-controls p,.control-set{display:none!important}.session-main{margin:0!important;padding:0!important;max-width:none!important}.session-title{margin:0 0 12px!important}.session-title h1{font-size:28px!important;line-height:1.3!important;margin:0!important}.session-grid{display:grid!important;grid-template-columns:1fr 1fr!important;gap:16px!important}.movement-panel{border:1px solid #dce1dd!important;overflow:hidden!important;background:white!important}.demo-reference{height:310px!important;padding:0!important}.demo-reference img{height:310px!important;width:100%!important;object-fit:contain!important}.coach-panel{padding:18px!important;border:1px solid #dce1dd!important;display:block!important}.coach-message{min-height:0!important;margin:0!important;height:100px!important}.coach-message strong{font-size:28px!important;line-height:1.3!important}.rep-card{margin:8px 0 0!important;padding:10px 0!important}.metric-label{font-size:22px!important}.rep-num{font-size:70px!important;line-height:1.1!important}.rep-main>span{font-size:26px!important}.session-controls{position:static!important;display:flex!important;margin-top:14px!important;padding:0!important;border:0!important;background:none!important;justify-content:flex-end!important;gap:14px!important;box-shadow:none!important}.session-controls button{font-size:22px!important;min-height:55px!important;padding:8px 24px!important}.set-bar{margin-top:12px!important}.cue-toast{padding:0!important;background:none!important;border:0!important}
`});
await page.waitForFunction(()=>Number(document.querySelector('.rep-num')?.textContent)>0,{},{timeout:45000});
await page.locator('.session').screenshot({path:'/Users/nasser/Desktop/Sports Disability Project/.visual-rework/english-ui/app-ui.png'});await browser.close();
